# Generated by Django 5.0.8 on 2024-08-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mirror', '0001_initial'), ('mirror', '0002_increase_link_length')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_sha1', models.CharField(blank=True, db_index=True, max_length=40)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'ordering': ['filename'],
                'unique_together': {('archive_sha1', 'filename', 'file_size')},
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('downloaded_at', models.DateTimeField()),
                ('sha1', models.CharField(blank=True, max_length=40)),
                ('md5', models.CharField(blank=True, max_length=32)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mirror_s3_key', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['link_class'],
                'abstract': False,
            },
        ),
    ]
