# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-19 20:35
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_sha1', models.CharField(blank=True, db_index=True, max_length=40)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=255)),
                ('downloaded_at', models.DateTimeField()),
                ('sha1', models.CharField(blank=True, max_length=40)),
                ('md5', models.CharField(blank=True, max_length=32)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mirror_s3_key', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['link_class'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='archivemember',
            unique_together=set([('archive_sha1', 'filename', 'file_size')]),
        ),
    ]
