# Generated by Django 1.9.7 on 2017-02-20 19:50
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shown_date_date', models.DateField(blank=True, null=True)),
                ('shown_date_precision', models.CharField(blank=True, choices=[(b'd', b'Day'), (b'm', b'Month'), (b'y', b'Year')], max_length=1)),
            ],
            options={
                'ordering': ('party__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompetitionPlacing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(blank=True, max_length=32)),
                ('position', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('start_date_date', models.DateField()),
                ('start_date_precision', models.CharField(choices=[(b'd', b'Day'), (b'm', b'Month'), (b'y', b'Year')], max_length=1)),
                ('end_date_date', models.DateField()),
                ('end_date_precision', models.CharField(choices=[(b'd', b'Day'), (b'm', b'Month'), (b'y', b'Year')], max_length=1)),
                ('is_online', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('woe_id', models.BigIntegerField(blank=True, null=True)),
                ('geonames_id', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('sceneorg_compofolders_done', models.BooleanField(default=False, help_text=b'Indicates that all compos at this party have been matched up with the corresponding scene.org directory')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='parties.Party')),
            ],
            options={
                'ordering': ['link_class'],
            },
        ),
        migrations.CreateModel(
            name='PartySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('twitter_username', models.CharField(blank=True, max_length=30)),
                ('pouet_party_id', models.IntegerField(blank=True, null=True, verbose_name=b'Pouet party ID')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Party series',
            },
        ),
        migrations.CreateModel(
            name='PartySeriesDemozoo0Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demozoo0_id', models.IntegerField(blank=True, null=True, verbose_name=b'Demozoo v0 ID')),
                ('party_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demozoo0_ids', to='parties.PartySeries')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'results')),
                ('filesize', models.IntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_files', to='parties.Party')),
            ],
        ),
    ]
