# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
        ('parties', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invitations',
            field=models.ManyToManyField(blank=True, related_name='invitation_parties', to='productions.Production'),
        ),
        migrations.AddField(
            model_name='party',
            name='party_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='parties.PartySeries'),
        ),
        migrations.AddField(
            model_name='party',
            name='releases',
            field=models.ManyToManyField(blank=True, related_name='release_parties', to='productions.Production'),
        ),
        migrations.AddField(
            model_name='competitionplacing',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placings', to='parties.Competition'),
        ),
        migrations.AddField(
            model_name='competitionplacing',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_placings', to='productions.Production'),
        ),
        migrations.AddField(
            model_name='competition',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='parties.Party'),
        ),
        migrations.AddField(
            model_name='competition',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.Platform'),
        ),
        migrations.AddField(
            model_name='competition',
            name='production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productions.ProductionType'),
        ),
        migrations.AlterUniqueTogether(
            name='partyexternallink',
            unique_together=set([('link_class', 'parameter', 'party')]),
        ),
    ]
