# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_increase_link_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.Platform'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productions.ProductionType'),
        ),
    ]
