# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 00:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_add_party_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
