# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 18:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import parties.models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_remove_production_default_screenshot'),
        ('parties', '0004_set_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='share_image_file',
            field=models.ImageField(blank=True, height_field=b'share_image_file_height', help_text=b'Upload an image file to display when sharing this party page on social media', upload_to=parties.models.party_share_image_upload_to, width_field=b'share_image_file_width'),
        ),
        migrations.AddField(
            model_name='party',
            name='share_image_file_height',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='share_image_file_url',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='share_image_file_width',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='share_screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productions.Screenshot'),
        ),
    ]
