# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_set_on_delete'),
        ('parties', '0005_party_search_title'),
    ]

    operations = [
    ]
