# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 00:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_party_share_image'),
        ('parties', '0005_party_search_title'),
    ]

    operations = [
    ]
