# Generated by Django 1.11.29 on 2020-11-19 23:15
import django.core.files.storage
from django.db import migrations, models

import parties.models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_search_document_noneditable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='shown_date_precision',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='end_date_precision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='sceneorg_compofolders_done',
            field=models.BooleanField(default=False, help_text='Indicates that all compos at this party have been matched up with the corresponding scene.org directory'),
        ),
        migrations.AlterField(
            model_name='party',
            name='share_image_file',
            field=models.ImageField(blank=True, height_field='share_image_file_height', help_text='Upload an image file to display when sharing this party page on social media', upload_to=parties.models.party_share_image_upload_to, width_field='share_image_file_width'),
        ),
        migrations.AlterField(
            model_name='party',
            name='start_date_precision',
            field=models.CharField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
        migrations.AlterField(
            model_name='partyseries',
            name='pouet_party_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pouet party ID'),
        ),
        migrations.AlterField(
            model_name='partyseriesdemozoo0reference',
            name='demozoo0_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Demozoo v0 ID'),
        ),
        migrations.AlterField(
            model_name='resultsfile',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='results'),
        ),
    ]
