# Generated by Django 2.2.17 on 2021-01-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0017_membership_group_limit_choices'),
        ('parties', '0008_py3_strings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisers', to='parties.Party')),
                ('releaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_organised', to='demoscene.Releaser')),
            ],
        ),
    ]
