# Generated by Django 2.2.17 on 2021-01-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
