# Generated by Django 2.2.17 on 2021-01-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_party_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='woe_id',
        ),
    ]
