# Generated by Django 4.0.8 on 2023-10-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_remove_party_woe_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartySeriesDemozoo0Reference',
        ),
    ]
