# Generated by Django 4.0.8 on 2023-10-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_delete_partyseriesdemozoo0reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySeriesExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('party_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='parties.partyseries')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'party_series')},
            },
        ),
    ]
