# Generated by Django 4.0.8 on 2023-10-14 00:50

from django.db import migrations


def populate_party_series_external_links(apps, schema_editor):
    PartySeries = apps.get_model("parties", "PartySeries")
    PartySeriesExternalLink = apps.get_model("parties", "PartySeriesExternalLink")
    db_alias = schema_editor.connection.alias
    for party_series in PartySeries.objects.using(db_alias).all():
        if party_series.pouet_party_id:
            PartySeriesExternalLink.objects.using(db_alias).get_or_create(
                party_series=party_series,
                link_class='PouetPartySeries',
                parameter=party_series.pouet_party_id
            )
        if party_series.twitter_username:
            PartySeriesExternalLink.objects.using(db_alias).get_or_create(
                party_series=party_series,
                link_class='TwitterAccount',
                parameter=party_series.twitter_username
            )


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0013_partyseriesexternallink'),
    ]

    operations = [
        migrations.RunPython(populate_party_series_external_links, migrations.RunPython.noop)
    ]
