version: "3.8"
services:
  demozoo-web:
    container_name: demozoo-web
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $PWD
        target: /home/demozoo
  demozoo-db:
    container_name: demozoo-db
    image: postgres:10.10
    restart: always
    env_file:
      - db.env
