version: "3.7"
services:
  demozoo-web:
    container_name: demozoo-web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $PWD
        target: /home/demozoo
  demozoo-db:
    container_name: demozoo-db
    image: postgres:10.10
    restart: always
    env_file:
      - db.env