# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 20:38
from django.db import migrations


def create_permission(apps, schema):
    ContentType = apps.get_model('contenttypes', 'contenttype')
    Permission = apps.get_model('auth', 'permission')

    ct, created = ContentType.objects.get_or_create(model='releaser', app_label='demoscene')
    perm, created = Permission.objects.get_or_create(content_type=ct,
                                                     codename='view_releaser_real_names',
                                                     defaults={'name': 'Can view non-public real names'})


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_permission)]
