# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-22 00:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0004_blacklistedtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
