# Generated by Django 1.11.8 on 2018-03-05 02:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0006_add_releaser_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='nickvariant',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
