# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0010_releaserexternallink_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaser',
            name='locked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
