# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 22:39
from django.db import migrations


def clear_private_real_names(apps, schema_editor):
    Releaser = apps.get_model("demoscene", "Releaser")
    db_alias = schema_editor.connection.alias
    Releaser.objects.using(db_alias).filter(show_first_name=False).update(first_name='')
    Releaser.objects.using(db_alias).filter(show_surname=False).update(surname='')


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0012_remove_admin_search'),
    ]

    operations = [
        migrations.RunPython(clear_private_real_names, migrations.RunPython.noop)
    ]
