# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 15:41
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0013_clear_private_real_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaser',
            name='show_first_name',
        ),
        migrations.RemoveField(
            model_name='releaser',
            name='show_surname',
        ),
    ]
