# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0014_remove_show_name_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releaser',
            options={'ordering': ['name'], 'permissions': (('change_releaser_real_names', 'Can change non-public real names'),)},
        ),
    ]
