# Generated by Django 2.0.13 on 2020-11-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0016_py3_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(limit_choices_to={'is_group': True}, on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='demoscene.Releaser'),
        ),
    ]
