# Generated by Django 3.1.7 on 2021-03-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0018_remove_releaser_woe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaser',
            name='hide_from_search_engines',
            field=models.BooleanField(default=False),
        ),
    ]
