# Generated by Django 5.0.8 on 2024-08-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0020_decode_asciiarena_params'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='edit',
            new_name='demoscene_e_focus_c_210c7b_idx',
            old_fields=('focus_content_type', 'focus_object_id'),
        ),
        migrations.RenameIndex(
            model_name='edit',
            new_name='demoscene_e_focus2__bb354d_idx',
            old_fields=('focus2_content_type', 'focus2_object_id'),
        ),
    ]
