# Generated by Django 5.0.8 on 2024-08-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pouet', '0001_initial'), ('pouet', '0002_groupmatchinfo'), ('pouet', '0003_downloadlink')]

    initial = True

    dependencies = [
        ('demoscene', '0009_search_document_noneditable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouet_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('demozoo_id', models.IntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouet_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField()),
                ('groups', models.ManyToManyField(related_name='productions', to='pouet.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_production_count', models.IntegerField()),
                ('unmatched_demozoo_production_count', models.IntegerField()),
                ('unmatched_pouet_production_count', models.IntegerField()),
                ('releaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoscene.releaser')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('link_type', models.CharField(max_length=255)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='pouet.production')),
            ],
        ),
    ]
