# Generated by Django 5.1 on 2024-10-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouet', '0001_squashed_0003_downloadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='download_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
