# Generated by Django 4.0.8 on 2023-01-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouet', '0004_production_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='cdc_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='vote_down_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='vote_pig_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='vote_up_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
