# Generated by Django 4.0.8 on 2023-01-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouet', '0005_production_cdc_count_production_popularity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouet_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='platforms',
            field=models.ManyToManyField(related_name='productions', to='pouet.platform'),
        ),
        migrations.AddField(
            model_name='production',
            name='types',
            field=models.ManyToManyField(related_name='productions', to='pouet.productiontype'),
        ),
    ]
