# Generated by Django 4.0.8 on 2023-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouet', '0007_competitiontype_party_competitionplacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='release_date_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='release_date_precision',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
    ]
