# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.CharField(choices=[(b'add', b'object added'), (b'edit', b'object edited'), (b'delete', b'object deleted')], max_length=6)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='change',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
