from django.urls import path

from productions.views import graphics as graphic_views
from productions.views import music as music_views
from productions.views import productions as production_views


urlpatterns = [
    path("productions/", production_views.ProductionIndexView.as_view(), {}, "productions"),
    path("productions/<int:production_id>/", production_views.ProductionShowView.as_view(), {}, "production"),
    path(
        "productions/<int:production_id>/history/",
        production_views.ProductionHistoryView.as_view(),
        {},
        "production_history",
    ),
    path("productions/<int:production_id>/carousel/", production_views.carousel, {}, "production_carousel"),
    path("music/", music_views.MusicIndexView.as_view(), {}, "musics"),
    path("music/<int:production_id>/", music_views.MusicShowView.as_view(), {}, "music"),
    path(
        "music/<int:production_id>/edit_core_details/",
        production_views.EditCoreDetailsView.as_view(),
        {},
        "music_edit_core_details",
    ),
    path("music/new/", music_views.CreateMusicView.as_view(), {}, "new_music"),
    path("music/<int:production_id>/history/", music_views.MusicHistoryView.as_view(), {}, "music_history"),
    path("graphics/", graphic_views.GraphicsIndexView.as_view(), {}, "graphics"),
    path("graphics/<int:production_id>/", graphic_views.GraphicsShowView.as_view(), {}, "graphic"),
    path(
        "graphics/<int:production_id>/edit_core_details/",
        production_views.EditCoreDetailsView.as_view(),
        {},
        "graphics_edit_core_details",
    ),
    path("graphics/new/", graphic_views.CreateGraphicsView.as_view(), {}, "new_graphics"),
    path("graphics/<int:production_id>/history/", graphic_views.GraphicsHistoryView.as_view(), {}, "graphics_history"),
    path("productions/new/", production_views.CreateProductionView.as_view(), {}, "new_production"),
    path("productions/autocomplete/", production_views.autocomplete, {}),
    path("productions/autocomplete_tags/", production_views.autocomplete_tags, {}),
    path("productions/tagged/<str:tag_name>/", production_views.tagged, {}, "productions_tagged"),
    path(
        "productions/<int:production_id>/edit_core_details/",
        production_views.EditCoreDetailsView.as_view(),
        {},
        "production_edit_core_details",
    ),
    path(
        "productions/<int:production_id>/add_credit/",
        production_views.AddCreditView.as_view(),
        {},
        "production_add_credit",
    ),
    path(
        "productions/<int:production_id>/edit_credit/<int:nick_id>/",
        production_views.EditCreditView.as_view(),
        {},
        "production_edit_credit",
    ),
    path(
        "productions/<int:production_id>/delete_credit/<int:nick_id>/",
        production_views.delete_credit,
        {},
        "production_delete_credit",
    ),
    path(
        "productions/<int:production_id>/edit_notes/",
        production_views.EditNotesView.as_view(),
        {},
        "production_edit_notes",
    ),
    path(
        "productions/<int:production_id>/edit_external_links/",
        production_views.EditExternalLinksView.as_view(),
        {},
        "production_edit_external_links",
    ),
    path(
        "productions/<int:production_id>/edit_download_links/",
        production_views.EditDownloadLinksView.as_view(),
        {},
        "production_edit_download_links",
    ),
    path(
        "productions/<int:production_id>/add_screenshot/",
        production_views.AddScreenshotView.as_view(),
        {},
        "production_add_screenshot",
    ),
    path(
        "productions/<int:production_id>/add_artwork/",
        production_views.AddScreenshotView.as_view(),
        {"is_artwork_view": True},
        "production_add_artwork",
    ),
    path("productions/<int:production_id>/screenshots/", production_views.screenshots, {}, "production_screenshots"),
    path("productions/<int:production_id>/artwork/", production_views.artwork, {}, "production_artwork"),
    path(
        "productions/<int:production_id>/screenshots/edit/",
        production_views.edit_screenshots,
        {},
        "production_edit_screenshots",
    ),
    path("productions/<int:production_id>/artwork/edit/", production_views.edit_artwork, {}, "production_edit_artwork"),
    path(
        "productions/<int:production_id>/delete_screenshot/<int:screenshot_id>/",
        production_views.DeleteScreenshotView.as_view(),
        {},
        "production_delete_screenshot",
    ),
    path(
        "productions/<int:production_id>/delete_artwork/<int:screenshot_id>/",
        production_views.DeleteArtworkView.as_view(),
        {},
        "production_delete_artwork",
    ),
    path(
        "productions/<int:production_id>/edit_soundtracks/",
        production_views.edit_soundtracks,
        {},
        "production_edit_soundtracks",
    ),
    path(
        "productions/<int:production_id>/edit_pack_contents/",
        production_views.edit_pack_contents,
        {},
        "production_edit_pack_contents",
    ),
    path(
        "productions/<int:production_id>/edit_tags/",
        production_views.ProductionEditTagsView.as_view(),
        {},
        "production_edit_tags",
    ),
    path(
        "productions/<int:production_id>/add_tag/",
        production_views.ProductionAddTagView.as_view(),
        {},
        "production_add_tag",
    ),
    path(
        "productions/<int:production_id>/remove_tag/",
        production_views.ProductionRemoveTagView.as_view(),
        {},
        "production_remove_tag",
    ),
    path(
        "productions/<int:production_id>/delete/",
        production_views.DeleteProductionView.as_view(),
        {},
        "delete_production",
    ),
    path(
        "productions/<int:production_id>/add_blurb/",
        production_views.AddBlurbView.as_view(),
        {},
        "production_add_blurb",
    ),
    path(
        "productions/<int:production_id>/edit_blurb/<int:blurb_id>/",
        production_views.EditBlurbView.as_view(),
        {},
        "production_edit_blurb",
    ),
    path(
        "productions/<int:production_id>/delete_blurb/<int:blurb_id>/",
        production_views.DeleteBlurbView.as_view(),
        {},
        "production_delete_blurb",
    ),
    path(
        "productions/<int:production_id>/edit_info/",
        production_views.EditInfoFilesView.as_view(),
        {},
        "production_edit_info_files",
    ),
    path("productions/<int:production_id>/info/<int:file_id>/", production_views.info_file, {}, "production_info_file"),
    path("productions/<int:production_id>/lock/", production_views.LockProductionView.as_view(), {}, "lock_production"),
    path("productions/<int:production_id>/protected/", production_views.protected, {}, "production_protected"),
]
