# Generated by Django 3.1.7 on 2021-07-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0011_remove_party_woe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='parties.party')),
            ],
            options={
                'unique_together': {('party', 'name')},
            },
        ),
    ]
