# Generated by Django 5.0.8 on 2024-08-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tournaments', '0001_initial'), ('tournaments', '0002_entry_phase_phasestaffmember'), ('tournaments', '0003_phasestaffmember_ordering'), ('tournaments', '0004_entry_thumbnail'), ('tournaments', '0005_alter_phasestaffmember_role_add_vj'), ('tournaments', '0006_tournamentexternallink_phaseexternallink_and_more'), ('tournaments', '0007_entry_source_file')]

    initial = True

    dependencies = [
        ('demoscene', '0019_releaser_hide_from_search_engines'),
        ('parties', '0011_remove_party_woe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='parties.party')),
            ],
            options={
                'unique_together': {('party', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Only if nick is empty', max_length=255)),
                ('ranking', models.CharField(blank=True, max_length=32)),
                ('position', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=32)),
                ('nick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='demoscene.nick')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.phase')),
                ('original_image_sha1', models.CharField(blank=True, editable=False, max_length=40)),
                ('thumbnail_height', models.IntegerField(blank=True, editable=False, null=True)),
                ('thumbnail_url', models.CharField(blank=True, editable=False, max_length=255)),
                ('thumbnail_width', models.IntegerField(blank=True, editable=False, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PhaseStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Only if nick is empty', max_length=255)),
                ('role', models.CharField(choices=[('commentary', 'Commentary'), ('dj_set', 'DJ set'), ('live_music', 'Live music'), ('vj', 'VJ')], max_length=50)),
                ('nick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_staff', to='demoscene.nick')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tournaments.phase')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='TournamentExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='PhaseExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.phase')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='EntryExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.entry')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'entry')},
            },
        ),
    ]
