# Generated by Django 3.1.13 on 2021-07-09 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0019_releaser_hide_from_search_engines'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PhaseStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Only if nick is empty', max_length=255)),
                ('role', models.CharField(choices=[('commentary', 'Commentary'), ('dj_set', 'DJ set'), ('live_music', 'Live music')], max_length=50)),
                ('nick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_staff', to='demoscene.nick')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tournaments.phase')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Only if nick is empty', max_length=255)),
                ('ranking', models.CharField(blank=True, max_length=32)),
                ('position', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=32)),
                ('nick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='demoscene.nick')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.phase')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
