# Generated by Django 4.0.8 on 2023-10-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_entry_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasestaffmember',
            name='role',
            field=models.CharField(choices=[('commentary', 'Commentary'), ('dj_set', 'DJ set'), ('live_music', 'Live music'), ('vj', 'VJ')], max_length=50),
        ),
    ]
