# Generated by Django 4.0.8 on 2023-10-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_phasestaffmember_role_add_vj'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='PhaseExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.phase')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='EntryExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tournaments.entry')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'entry')},
            },
        ),
    ]
