# Generated by Django 4.0.8 on 2023-10-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentexternallink_phaseexternallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
