# Generated by Django 5.0.8 on 2024-08-17 13:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.migrations.operations.special
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bbs', '0001_initial'), ('bbs', '0002_bbs_bbstros'), ('bbs', '0003_operator'), ('bbs', '0004_affiliation'), ('bbs', '0005_affiliation_role_optional'), ('bbs', '0006_bbs_search_title'), ('bbs', '0007_populate_search_title'), ('bbs', '0008_search_document'), ('bbs', '0009_textad'), ('bbs', '0010_add_ehq_role'), ('bbs', '0011_bbs_tags'), ('bbs', '0012_operator_is_current'), ('bbs', '0013_bbs_names'), ('bbs', '0014_bbsexternallink')]

    initial = True

    dependencies = [
        ('demoscene', '0018_remove_releaser_woe_id'),
        ('productions', '0019_soundtrack_limit_choices'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geonames_id', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bbstros', models.ManyToManyField(blank=True, related_name='bbses', to='productions.production')),
                ('search_title', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'BBSes',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sysop', 'Sysop'), ('co-sysop', 'Co-Sysop')], max_length=50)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='bbs.bbs')),
                ('releaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbses_operated', to='demoscene.releaser')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('010-whq', 'WHQ'), ('020-hq', 'HQ'), ('030-memberboard', 'Memberboard'), ('040-distsite', 'Distsite')], max_length=50)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bbs.bbs')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_affiliations', to='demoscene.releaser')),
            ],
        ),
        migrations.AddField(
            model_name='bbs',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='bbs',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='bbs_bbs_search__62f7ad_gin'),
        ),
        migrations.CreateModel(
            name='TextAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('filesize', models.IntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.FileField(blank=True, upload_to='bbs_ads')),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_ads', to='bbs.bbs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='role',
            field=models.CharField(blank=True, choices=[('010-whq', 'WHQ'), ('015-ehq', 'EHQ'), ('020-hq', 'HQ'), ('030-memberboard', 'Memberboard'), ('040-distsite', 'Distsite')], max_length=50),
        ),
        migrations.AddField(
            model_name='bbs',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='bbs',
            options={'ordering': ['name'], 'verbose_name_plural': 'BBSes'},
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='bbs.bbs')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('bbs', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BBSExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('source', models.CharField(blank=True, editable=False, help_text='Identifier to indicate where this link came from - e.g. manual (entered via form), match, auto', max_length=32)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='bbs.bbs')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'bbs')},
            },
        ),
    ]
