# Generated by Django 2.2.17 on 2021-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0019_soundtrack_limit_choices'),
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='bbstros',
            field=models.ManyToManyField(blank=True, related_name='bbses', to='productions.Production'),
        ),
    ]
