# Generated by Django 2.2.17 on 2021-01-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0018_remove_releaser_woe_id'),
        ('bbs', '0002_bbs_bbstros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sysop', 'Sysop'), ('co-sysop', 'Co-Sysop')], max_length=50)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='bbs.BBS')),
                ('releaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbses_operated', to='demoscene.Releaser')),
            ],
        ),
    ]
