# Generated by Django 2.2.17 on 2021-01-18 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0018_remove_releaser_woe_id'),
        ('bbs', '0003_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('010-whq', 'WHQ'), ('020-hq', 'HQ'), ('030-memberboard', 'Memberboard'), ('040-distsite', 'Distsite')], max_length=50)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bbs.BBS')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_affiliations', to='demoscene.Releaser')),
            ],
        ),
    ]
