# Generated by Django 2.2.17 on 2021-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='role',
            field=models.CharField(blank=True, choices=[('010-whq', 'WHQ'), ('020-hq', 'HQ'), ('030-memberboard', 'Memberboard'), ('040-distsite', 'Distsite')], max_length=50),
        ),
    ]
