# Generated by Django 2.2.17 on 2021-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_affiliation_role_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
