# Generated by Django 2.2.17 on 2021-01-24 16:18

from django.db import migrations

from demoscene.utils.text import generate_search_title


def populate_search_title(apps, schema_editor):
    BBS = apps.get_model("bbs", "BBS")
    for bbs in BBS.objects.all():
        bbs.search_title = generate_search_title(bbs.name)
        bbs.save(update_fields=['search_title'])


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_bbs_search_title'),
    ]

    operations = [
        migrations.RunPython(populate_search_title, migrations.RunPython.noop),
    ]
