# Generated by Django 2.2.17 on 2021-01-24 16:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_populate_search_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='bbs',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='bbs_bbs_search__62f7ad_gin'),
        ),
    ]
