# Generated by Django 3.1.7 on 2021-03-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_search_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('filesize', models.IntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.FileField(blank=True, upload_to='bbs_ads')),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_ads', to='bbs.bbs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
