# Generated by Django 3.1.7 on 2021-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_textad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='role',
            field=models.CharField(blank=True, choices=[('010-whq', 'WHQ'), ('015-ehq', 'EHQ'), ('020-hq', 'HQ'), ('030-memberboard', 'Memberboard'), ('040-distsite', 'Distsite')], max_length=50),
        ),
    ]
