# Generated by Django 3.1.7 on 2021-04-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_bbs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
