# Generated by Django 3.1.7 on 2021-04-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_operator_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={'ordering': ['name'], 'verbose_name_plural': 'BBSes'},
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='bbs.bbs')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('bbs', 'name')},
            },
        ),
    ]
