# Generated by Django 3.1.7 on 2021-06-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_bbs_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_class', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=4096)),
                ('source', models.CharField(blank=True, editable=False, help_text='Identifier to indicate where this link came from - e.g. manual (entered via form), match, auto', max_length=32)),
                ('bbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='bbs.bbs')),
            ],
            options={
                'ordering': ['link_class'],
                'unique_together': {('link_class', 'parameter', 'bbs')},
            },
        ),
    ]
