# Generated by Django 5.1 on 2024-11-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_squashed_0014_bbsexternallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bbs',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
