from djapian.tests.query import *
from djapian.tests.index import *
from djapian.tests.search import *
from djapian.tests.common import *
from djapian.tests.pagination import *
from djapian.tests.filtering import *
from djapian.tests.pickling import *
from djapian.tests.collapse import *
from djapian.tests.stem import *
