# Generated by Django 3.1.7 on 2021-04-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
