# Generated by Django 5.1.11 on 2026-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneorg', '0001_squashed_0002_set_path_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(db_index=True, max_length=1023, unique=True),
        ),
    ]
