# Generated by Django 5.0.8 on 2024-08-17 13:26

import django.db.models.deletion
import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('homepage', '0001_initial'), ('homepage', '0002_banner_hide_text'), ('homepage', '0003_py3_strings'), ('homepage', '0004_newsstory_is_public_blank'), ('homepage', '0005_banner_small_print')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', help_text='Will be cropped to 2.5 : 1 aspect ratio. Recommended size: 832x333', upload_to=homepage.models.banner_image_upload_to, width_field='image_width')),
                ('image_width', models.IntegerField(editable=False)),
                ('image_height', models.IntegerField(editable=False)),
                ('image_url', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', help_text='Recommended size: 100x100', upload_to=homepage.models.news_image_upload_to, width_field='image_width')),
                ('image_width', models.IntegerField(editable=False)),
                ('image_height', models.IntegerField(editable=False)),
                ('image_url', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.newsimage')),
            ],
            options={
                'verbose_name_plural': 'News stories',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('show_for_anonymous_users', models.BooleanField(default=True)),
                ('show_for_logged_in_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.bannerimage')),
                ('hide_text', models.BooleanField(default=False, help_text="Instead of displaying text, use it as fallback text for people who can't see the image")),
                ('small_print', models.TextField(blank=True, help_text='Shown below the banner, for picture credits etc. Markdown supported')),
            ],
        ),
    ]
