# Generated by Django 1.9.7 on 2017-02-20 20:16
import django.db.models.deletion
from django.db import migrations, models

import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('url', models.CharField(max_length=255, verbose_name=b'URL')),
                ('show_for_anonymous_users', models.BooleanField(default=True)),
                ('show_for_logged_in_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=b'image_height', help_text=b'Will be cropped to 2.5 : 1 aspect ratio. Recommended size: 832x333', upload_to=homepage.models.banner_image_upload_to, width_field=b'image_width')),
                ('image_width', models.IntegerField(editable=False)),
                ('image_height', models.IntegerField(editable=False)),
                ('image_url', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=b'image_height', help_text=b'Recommended size: 100x100', upload_to=homepage.models.news_image_upload_to, width_field=b'image_width')),
                ('image_width', models.IntegerField(editable=False)),
                ('image_height', models.IntegerField(editable=False)),
                ('image_url', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.NewsImage')),
            ],
            options={
                'verbose_name_plural': 'News stories',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homepage.BannerImage'),
        ),
    ]
