# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hide_text',
            field=models.BooleanField(default=False, help_text=b"Instead of displaying text, use it as fallback text for people who can't see the image"),
        ),
    ]
