# Generated by Django 3.2.12 on 2022-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_newsstory_is_public_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='small_print',
            field=models.TextField(blank=True, help_text='Shown below the banner, for picture credits etc. Markdown supported'),
        ),
    ]
