# Generated by Django 4.0.8 on 2024-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_set_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='residue',
            field=models.BooleanField(default=False),
        ),
    ]
