# Generated by Django 5.1.2 on 2025-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntrustedLinkIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_part', models.CharField(help_text="Enter identifier for an untrusted link. This is usually a part of an URL for example 'goo.gl'.", max_length=64)),
            ],
        ),
    ]
