# Generated by Django 5.0.8 on 2024-08-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('janeway', '0001_initial'), ('janeway', '0002_add_releases_and_credits'), ('janeway', '0003_add_indexes'), ('janeway', '0004_authormatchinfo'), ('janeway', '0005_add_country_code_and_company_to_author'), ('janeway', '0006_downloads_and_feature_links'), ('janeway', '0007_release_platform'), ('janeway', '0008_release_date'), ('janeway', '0009_screenshot'), ('janeway', '0010_screenshot_suffix'), ('janeway', '0011_py3_strings')]

    initial = True

    dependencies = [
        ('demoscene', '0010_releaserexternallink_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('real_name', models.CharField(blank=True, max_length=255)),
                ('real_name_hidden', models.BooleanField(default=False)),
                ('is_group', models.BooleanField()),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('is_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('founder', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='janeway.author')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='janeway.author')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='janeway.author')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('supertype', models.CharField(choices=[('production', 'Production'), ('graphics', 'Graphics'), ('music', 'Music')], max_length=20)),
                ('author_names', models.ManyToManyField(related_name='authored_releases', to='janeway.name')),
                ('platform', models.CharField(blank=True, choices=[('ocs', 'Amiga OCS/ECS'), ('aga', 'Amiga AGA'), ('ppc', 'Amiga PPC/RTG')], max_length=20)),
                ('release_date_date', models.DateField(blank=True, null=True)),
                ('release_date_precision', models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='janeway.release')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorMatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_production_count', models.IntegerField()),
                ('unmatched_demozoo_production_count', models.IntegerField()),
                ('unmatched_janeway_production_count', models.IntegerField()),
                ('releaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoscene.releaser')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='janeway.release')),
            ],
        ),
        migrations.CreateModel(
            name='PackContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_in', to='janeway.release')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_contents', to='janeway.release')),
            ],
        ),
        migrations.CreateModel(
            name='SoundtrackLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundtrack_links', to='janeway.release')),
                ('soundtrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances_as_soundtrack', to='janeway.release')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='janeway.name')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='janeway.release')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField()),
                ('url', models.URLField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='janeway.release')),
                ('suffix', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
