# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 16:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='janeway.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('supertype', models.CharField(choices=[(b'production', b'Production'), (b'graphics', b'Graphics'), (b'music', b'Music')], max_length=20)),
                ('author_names', models.ManyToManyField(related_name='authored_releases', to='janeway.Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='janeway.Release')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='janeway.Release'),
        ),
    ]
