# Generated by Django 1.11.8 on 2019-07-13 17:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0002_add_releases_and_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
