# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-13 18:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoscene', '0010_releaserexternallink_source'),
        ('janeway', '0003_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_production_count', models.IntegerField()),
                ('unmatched_demozoo_production_count', models.IntegerField()),
                ('unmatched_janeway_production_count', models.IntegerField()),
                ('releaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoscene.Releaser')),
            ],
        ),
    ]
