# Generated by Django 1.11.8 on 2019-07-17 10:03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0004_authormatchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='author',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
