# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0005_add_country_code_and_company_to_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='janeway.Release')),
            ],
        ),
        migrations.CreateModel(
            name='PackContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_in', to='janeway.Release')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_contents', to='janeway.Release')),
            ],
        ),
        migrations.CreateModel(
            name='SoundtrackLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundtrack_links', to='janeway.Release')),
                ('soundtrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances_as_soundtrack', to='janeway.Release')),
            ],
        ),
        migrations.AlterField(
            model_name='credit',
            name='janeway_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
