# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 15:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0006_downloads_and_feature_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='platform',
            field=models.CharField(blank=True, choices=[(b'ocs', b'Amiga OCS/ECS'), (b'aga', b'Amiga AGA'), (b'ppc', b'Amiga PPC/RTG')], max_length=20),
        ),
    ]
