# Generated by Django 1.11.8 on 2019-07-20 01:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0007_release_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_date_precision',
            field=models.CharField(blank=True, choices=[(b'd', b'Day'), (b'm', b'Month'), (b'y', b'Year')], max_length=1),
        ),
    ]
