# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-03 22:56
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0009_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='suffix',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
