# Generated by Django 1.11.29 on 2020-11-19 23:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0010_screenshot_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='platform',
            field=models.CharField(blank=True, choices=[('ocs', 'Amiga OCS/ECS'), ('aga', 'Amiga AGA'), ('ppc', 'Amiga PPC/RTG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date_precision',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
        migrations.AlterField(
            model_name='release',
            name='supertype',
            field=models.CharField(choices=[('production', 'Production'), ('graphics', 'Graphics'), ('music', 'Music')], max_length=20),
        ),
    ]
