# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 20:27
from django.db import migrations


def create_productiontypes(apps, schema):
    ProductionType = apps.get_model('productions', 'productiontype')
    if ProductionType.objects.exists():
        return

    productiontypes = [
    {
        "path": "0006",
        "depth": 1,
        "numchild": 0,
        "name": "Demo",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A000R",
        "depth": 2,
        "numchild": 0,
        "name": "64K Intro",
        "position": 100,
        "internal_name": ""
    },
    {
        "path": "000A000L",
        "depth": 2,
        "numchild": 0,
        "name": "4K Intro",
        "position": 70,
        "internal_name": ""
    },
    {
        "path": "000A",
        "depth": 1,
        "numchild": 16,
        "name": "Intro",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000D0001",
        "depth": 2,
        "numchild": 0,
        "name": "Diskmag",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000K",
        "depth": 1,
        "numchild": 0,
        "name": "Tool",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000F",
        "depth": 1,
        "numchild": 1,
        "name": "Musicdisk",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000J",
        "depth": 1,
        "numchild": 0,
        "name": "Slideshow",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000G",
        "depth": 1,
        "numchild": 1,
        "name": "Pack",
        "position": 0,
        "internal_name": "pack"
    },
    {
        "path": "000A000Q",
        "depth": 2,
        "numchild": 0,
        "name": "40k Intro",
        "position": 90,
        "internal_name": ""
    },
    {
        "path": "000B",
        "depth": 1,
        "numchild": 0,
        "name": "Invitation",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000F0001",
        "depth": 2,
        "numchild": 0,
        "name": "Chip Music Pack",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A0006",
        "depth": 2,
        "numchild": 0,
        "name": "Cracktro",
        "position": 5,
        "internal_name": ""
    },
    {
        "path": "000E",
        "depth": 1,
        "numchild": 3,
        "name": "Music",
        "position": 0,
        "internal_name": "music"
    },
    {
        "path": "000A0007",
        "depth": 2,
        "numchild": 0,
        "name": "32b Intro",
        "position": 10,
        "internal_name": ""
    },
    {
        "path": "000A000A",
        "depth": 2,
        "numchild": 0,
        "name": "64b Intro",
        "position": 20,
        "internal_name": ""
    },
    {
        "path": "000A000C",
        "depth": 2,
        "numchild": 0,
        "name": "128b Intro",
        "position": 30,
        "internal_name": ""
    },
    {
        "path": "000A000E",
        "depth": 2,
        "numchild": 0,
        "name": "256b Intro",
        "position": 40,
        "internal_name": ""
    },
    {
        "path": "000A000G",
        "depth": 2,
        "numchild": 0,
        "name": "512b Intro",
        "position": 50,
        "internal_name": ""
    },
    {
        "path": "000A000I",
        "depth": 2,
        "numchild": 0,
        "name": "1K Intro",
        "position": 60,
        "internal_name": ""
    },
    {
        "path": "000A000P",
        "depth": 2,
        "numchild": 0,
        "name": "32K Intro",
        "position": 80,
        "internal_name": ""
    },
    {
        "path": "0009",
        "depth": 1,
        "numchild": 6,
        "name": "Graphics",
        "position": 0,
        "internal_name": "graphics"
    },
    {
        "path": "00090008",
        "depth": 2,
        "numchild": 0,
        "name": "ASCII",
        "position": 0,
        "internal_name": "ascii"
    },
    {
        "path": "00090009",
        "depth": 2,
        "numchild": 0,
        "name": "ASCII Collection",
        "position": 0,
        "internal_name": "ascii-collection"
    },
    {
        "path": "0009000E",
        "depth": 2,
        "numchild": 0,
        "name": "ANSI",
        "position": 10,
        "internal_name": "ansi"
    },
    {
        "path": "0009000F",
        "depth": 2,
        "numchild": 0,
        "name": "Artpack",
        "position": 20,
        "internal_name": "artpack"
    },
    {
        "path": "0009000G",
        "depth": 2,
        "numchild": 1,
        "name": "Procedural Graphics",
        "position": 30,
        "internal_name": "exe-graphics"
    },
    {
        "path": "0009000G0003",
        "depth": 3,
        "numchild": 0,
        "name": "4K Procedural Graphics",
        "position": 10,
        "internal_name": "4k-exe-graphics"
    },
    {
        "path": "000E0006",
        "depth": 2,
        "numchild": 0,
        "name": "Tracked Music",
        "position": 0,
        "internal_name": "tracked-music"
    },
    {
        "path": "000E0005",
        "depth": 2,
        "numchild": 0,
        "name": "Streaming Music",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000E0004",
        "depth": 2,
        "numchild": 2,
        "name": "Executable Music",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000E00040002",
        "depth": 3,
        "numchild": 0,
        "name": "32K Executable Music",
        "position": 50,
        "internal_name": ""
    },
    {
        "path": "0008",
        "depth": 1,
        "numchild": 0,
        "name": "Game",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000L",
        "depth": 1,
        "numchild": 0,
        "name": "Video",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A000O",
        "depth": 2,
        "numchild": 0,
        "name": "16K Intro",
        "position": 75,
        "internal_name": ""
    },
    {
        "path": "0009000A",
        "depth": 2,
        "numchild": 0,
        "name": "Photo",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A000K",
        "depth": 2,
        "numchild": 0,
        "name": "2K Intro",
        "position": 65,
        "internal_name": ""
    },
    {
        "path": "000E00040004",
        "depth": 3,
        "numchild": 0,
        "name": "64K Executable Music",
        "position": 60,
        "internal_name": ""
    },
    {
        "path": "000A000U",
        "depth": 2,
        "numchild": 0,
        "name": "100K Intro",
        "position": 110,
        "internal_name": ""
    },
    {
        "path": "000A0005",
        "depth": 2,
        "numchild": 0,
        "name": "BBStro",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000H",
        "depth": 1,
        "numchild": 0,
        "name": "Performance",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A000M",
        "depth": 2,
        "numchild": 0,
        "name": "8K Intro",
        "position": 73,
        "internal_name": ""
    },
    {
        "path": "000I",
        "depth": 1,
        "numchild": 0,
        "name": "Report",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000M",
        "depth": 1,
        "numchild": 0,
        "name": "Votedisk",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000G0001",
        "depth": 2,
        "numchild": 0,
        "name": "Docsdisk",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000D",
        "depth": 1,
        "numchild": 3,
        "name": "Magazine",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000D0002",
        "depth": 2,
        "numchild": 0,
        "name": "Papermag",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000D0003",
        "depth": 2,
        "numchild": 0,
        "name": "Textmag",
        "position": 0,
        "internal_name": ""
    },
    {
        "path": "000A000T",
        "depth": 2,
        "numchild": 0,
        "name": "96K Intro",
        "position": 105,
        "internal_name": ""
    }]

    for pt in productiontypes:
        ProductionType.objects.create(**pt)


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_productiontypes)]
