# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 20:09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_default_productiontypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlink',
            name='parameter',
            field=models.CharField(max_length=4096),
        ),
    ]
