# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_production_authoraffiliationlinks_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='has_screenshot',
            field=models.BooleanField(default=False, editable=False, help_text=b'True if this prod has at least one (processed) screenshot'),
        ),
        migrations.RunSQL("UPDATE productions_production SET has_screenshot = (default_screenshot_id IS NOT NULL)", migrations.RunSQL.noop),
    ]
