# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-25 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_production_has_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='default_screenshot',
        ),
    ]
