# Generated by Django 1.11.8 on 2018-10-06 20:13
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0008_production_search_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
