# Generated by Django 1.11.8 on 2018-10-21 02:11
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0010_productionlink_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('filesize', models.IntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'nfo')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_files', to='productions.Production')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
