# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0012_infofile_default_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='locked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
