# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 17:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0013_production_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='data_source',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
