# Generated by Django 1.11.8 on 2019-07-18 18:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0014_credit_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='packmember',
            name='data_source',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='soundtracklink',
            name='data_source',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
