# Generated by Django 1.11.8 on 2019-11-03 23:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0015_soundtrack_packmember_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='data_source',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='janeway_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='janeway_suffix',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
