# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-31 18:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0016_screenshot_janeway_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansi',
            name='production',
        ),
        migrations.DeleteModel(
            name='Ansi',
        ),
    ]
