# Generated by Django 2.0.13 on 2020-11-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0018_py3_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtracklink',
            name='soundtrack',
            field=models.ForeignKey(limit_choices_to={'supertype': 'music'}, on_delete=django.db.models.deletion.CASCADE, related_name='appearances_as_soundtrack', to='productions.Production'),
        ),
    ]
