# Generated by Django 3.1.7 on 2021-04-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0020_production_hide_from_search_engines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infofile',
            options={'verbose_name': 'info file', 'verbose_name_plural': 'info files'},
        ),
    ]
