# Generated by Django 3.1.13 on 2021-08-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0021_infofile_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emulator', models.CharField(max_length=30)),
                ('launch_url', models.URLField(max_length=4096)),
                ('configuration', models.TextField(blank=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emulator_configs', to='productions.production')),
            ],
        ),
    ]
