# Generated by Django 3.1.13 on 2021-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0022_emulatorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emulatorconfig',
            name='emulator',
            field=models.CharField(choices=[('jsspeccy', 'JSSpeccy')], max_length=30),
        ),
    ]
