# Generated by Django 4.0.8 on 2023-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_emulator_config_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='thumbnail_url',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
