# Generated by Django 5.0.8 on 2024-08-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0024_alter_screenshot_thumbnail_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='production',
            new_name='productions_release_fc8d66_idx',
            old_fields=('release_date_date', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='productionlink',
            new_name='productions_link_cl_a8fd1a_idx',
            old_fields=('link_class', 'parameter'),
        ),
    ]
