# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import platforms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, height_field=b'photo_height', null=True, upload_to=platforms.models.photo_original_upload_to, width_field=b'photo_width')),
                ('photo_width', models.IntegerField(blank=True, editable=False, null=True)),
                ('photo_height', models.IntegerField(blank=True, editable=False, null=True)),
                ('thumbnail', models.ImageField(blank=True, editable=False, height_field=b'thumbnail_height', null=True, upload_to=platforms.models.thumbnail_upload_to, width_field=b'thumbnail_width')),
                ('thumbnail_width', models.IntegerField(blank=True, editable=False, null=True)),
                ('thumbnail_height', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
