# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 21:39
from __future__ import unicode_literals

from django.db import migrations


def make_default_platforms(apps, schema):
    Platform = apps.get_model('platforms', 'Platform')
    if Platform.objects.exists():
        return
    platforms = [
        {'name': 'ZX Spectrum'},
        {'name': 'Windows'},
        {'name': 'Commodore 64'},
        {'name': 'MS-Dos'},
        {'name': 'Amiga OCS/ECS'},
        {'name': 'Amiga AGA'},
        {'name': 'Linux'},
        {'name': 'BeOS'},
        {'name': 'Atari ST/E'},
        {'name': 'Mac OS X'},
        {'name': 'Browser'},
        {'name': 'Sony Playstation 1 (PSX)'},
        {'name': 'Console Handheld'},
        {'name': 'XBOX360'},
        {'name': 'Atari 8 bit'},
        {'name': 'Atari Falcon'},
        {'name': 'Mobile'},
        {'name': 'VIC-20'},
        {'name': 'Sega Megadrive/Genesis'},
        {'name': 'Sega Dreamcast'},
        {'name': 'Nintendo Wii'},
        {'name': 'Nintendo Entertainment System (NES)'},
        {'name': 'Amiga PPC/RTG'},
        {'name': 'Calculator'},
        {'name': 'Sony Playstation 2 (PS2)'},
        {'name': 'Sony Playstation Portable (PSP)'},
        {'name': 'Nintendo GameBoy Advance (GBA)'},
        {'name': 'MSX'},
        {'name': 'Nintendo DS (NDS)'},
        {'name': 'Nintendo SNES/Super FamiCom'},
        {'name': 'Acorn Archimedes'},
        {'name': 'Amstrad CPC'},
        {'name': 'Nintendo GameBoy Color (GBC)'},
        {'name': 'Nintendo GameBoy (GB)'},
        {'name': 'Nintendo 64 (N64)'},
        {'name': 'XBOX'},
        {'name': 'Commodore 16/Plus 4'},
        {'name': 'KC 85/Robotron KC 87'},
        {'name': 'Vectrex'},
        {'name': 'Sega Master System'},
        {'name': 'ZX81'},
        {'name': 'Javascript'},
        {'name': 'Flash'},
        {'name': 'Java'},
        {'name': 'Oric'},
        {'name': 'Atari Jaguar'},
        {'name': 'SAM Coupé'},
        {'name': 'Android'},
        {'name': 'Thomson'},
        {'name': 'Atari 2600 Video Computer System (VCS)'},
        {'name': 'Commodore 128'},
        {'name': 'Gamepark GP2X'},
        {'name': 'Apple II GS'},
        {'name': 'Atari TT'},
        {'name': 'Raspberry Pi'},
        {'name': 'Nintendo GameCube (NGC)'},
        {'name': 'Amstrad Plus'},
        {'name': 'Custom Hardware'},
        {'name': 'PMD 85'},
        {'name': 'Paper'},
        {'name': 'Vector-06C'},
        {'name': 'BBC Micro'},
        {'name': 'Apple II'},
        {'name': 'Sony Playstation 3 (PS3)'},
        {'name': 'ZX Spectrum Enhanced'},
        {'name': 'Atari Lynx'},
        {'name': 'Nintendo 3DS'},
        {'name': 'Gamepark 32 '},
        {'name': 'Electronika BK-0010/11M'},
        {'name': 'Enterprise'},
        {'name': 'NEC PC Engine'},
    ]

    for platform in platforms:
        Platform.objects.create(**platform)


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [migrations.RunPython(make_default_platforms)]
