# Generated by Django 1.11.8 on 2018-07-18 19:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_default_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Alternative name to be recognised in search filters such as platform:c64', max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='platforms.Platform')),
            ],
        ),
    ]
