# Generated by Django 1.11.29 on 2020-11-19 23:15
from django.db import migrations, models

import platforms.models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_platformalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', null=True, upload_to=platforms.models.photo_original_upload_to, width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, height_field='thumbnail_height', null=True, upload_to=platforms.models.thumbnail_upload_to, width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='platformalias',
            name='name',
            field=models.CharField(help_text='Alternative name to be recognised in search filters such as platform:c64', max_length=255),
        ),
    ]
