# Generated by Django 4.0.8 on 2023-10-30 01:58

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_py3_strings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
