# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productions', '0017_remove_ansi'),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='awards.Category')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to='productions.Production')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set([('user', 'production', 'category')]),
        ),
    ]
