# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_set_category_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='meteoriks-2020', max_length=255, unique=True, help_text="Used in URLs - /awards/[slug]/"),
            preserve_default=False,
        ),
    ]
