# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0005_event_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sticky', models.BooleanField(default=False, help_text='If set, this juror will not be removed in the event that they are absent from the feed of jury members')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='juror_feed_url',
            field=models.URLField(blank=True, help_text='URL to a list of juror SceneIDs', max_length=255),
        ),
        migrations.AddField(
            model_name='juror',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurors', to='awards.Event'),
        ),
        migrations.AddField(
            model_name='juror',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juror_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='juror',
            unique_together=set([('user', 'event')]),
        ),
    ]
