# Generated by Django 3.1.13 on 2021-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_emulator_config_choices'),
        ('awards', '0006_jurors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='production_types',
            field=models.ManyToManyField(blank=True, help_text='If set, these awards only accept recommendations for productions of these types', to='productions.ProductionType'),
        ),
    ]
