# Generated by Django 4.0.3 on 2022-12-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_py3_strings'),
        ('awards', '0007_event_production_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='If set, the candidates listing is filtered by these platforms', to='platforms.platform'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='If set, enables a candidates listing page at /awards/[slug]/[category]/', max_length=255),
        ),
    ]
