# Generated by Django 4.0.8 on 2023-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_category_platforms_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_recommendation_counts',
            field=models.BooleanField(default=False, help_text='If true, reports will show how many times a production has been recommended'),
        ),
    ]
