# Generated by Django 4.0.8 on 2023-10-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_emulator_config_choices'),
        ('awards', '0009_event_show_recommendation_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nominee', 'Nominee'), ('winner', 'Winner')], default='nominee', max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='awards.category')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_nominations', to='productions.production')),
            ],
            options={
                'unique_together': {('production', 'category')},
            },
        ),
    ]
