# Generated by Django 5.0.8 on 2024-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_squashed_0011_eventseries_event_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Used in URLs - /awards/[slug]/', max_length=255, unique=True),
        ),
    ]
