# Generated by Django 5.1.11 on 2025-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='screening_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable the interface for jurors to screen eligible productions'),
        ),
    ]
