# Generated by Django 5.1.11 on 2025-07-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_event_screening_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='production_types',
            new_name='recommendable_production_types',
        ),
    ]
