# Generated by Django 5.1.11 on 2025-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0014_rename_production_types_event_recommendable_production_types'),
        ('productions', '0001_squashed_0025_production_productionlink_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='screenable_production_types',
            field=models.ManyToManyField(blank=True, help_text='The set of production types to be presented to jurors for screening', related_name='+', to='productions.productiontype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recommendable_production_types',
            field=models.ManyToManyField(blank=True, help_text='If set, these awards only accept recommendations for productions of these types', related_name='+', to='productions.productiontype'),
        ),
    ]
