# Generated by Django 5.1.11 on 2025-07-08 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0015_event_screenable_production_types'),
        ('productions', '0001_squashed_0025_production_productionlink_index_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_decisions', to='awards.event')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_decisions', to='productions.production')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('production', 'event', 'user')},
            },
        ),
    ]
