# Generated by Django 5.1.11 on 2025-07-12 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0016_screeningdecision'),
        ('platforms', '0001_squashed_0005_platforms_set_case_insensitive_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="An option such as 'Oldschool' that jurors can filter on in the screening view.", max_length=255, unique=True)),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_groups', to='awards.eventseries')),
                ('platforms', models.ManyToManyField(help_text='Platforms that belong to this group.', related_name='platform_groups', to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Platform group',
                'verbose_name_plural': 'Platform groups',
            },
        ),
    ]
