# Generated by Django 5.1.11 on 2025-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0017_platformgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformgroup',
            name='include_no_platform',
            field=models.BooleanField(default=False, help_text='Whether to include productions with no associated platform.'),
        ),
    ]
