# Generated by Django 5.1.11 on 2025-07-19 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0018_platformgroup_include_no_platform'),
        ('productions', '0001_squashed_0025_production_productionlink_index_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='For raising issues and sharing information with other jurors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_comments', to='awards.event')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_comments', to='productions.production')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
